### ISSUE TITLE
decide what to do with the left, center, right slots for header and footer

### ISSUE THREAD

**Issue by sandros94** [Sandros94/ui#7]
They will stay, but I need to decide if the default behaviour is to keep them active and let the spacing be, or if no content is present let them collapse by default.

Current approach will be:
- Header: empty space will be cept, manual intervention is needed to hide sections
- Footer: empty space will be collapsed, manual intervention is needed to show empty sections.

**Comment by Sandros94** [comment]
I'm probably going to let them collapse if no content is passed
